import { TestCase } from './testDataset';

export const RULE_ENGINE_CATEGORIES = [
  'particle_hyphen', 'particle_joined', 'possessive_ning', 'reduplicative_hyphen',
  'bolmasa_person', 'xalos_xolos', 'suffix_li_lik', 'lar_giz',
] as const;

// Measurement-only cases. Unsupported and adversarial constructions are
// intentional: this dataset measures current behavior rather than gaming it.
export const RULE_ENGINE_TEST_DATASET: TestCase[] = [
  { id: 341, category: 'particle_hyphen', input: 'Men ertaga boramanku.', expectError: true, expectedWord: 'boramanku', expectedSuggestion: 'boraman-ku' },
  { id: 342, category: 'particle_hyphen', input: 'Bu ishni qilyapmizda.', expectError: true, expectedWord: 'qilyapmizda', expectedSuggestion: 'qilyapmiz-da' },
  { id: 343, category: 'particle_hyphen', input: 'Navbat endi menchi?', expectError: true, expectedWord: 'menchi', expectedSuggestion: 'men-chi' },
  { id: 344, category: 'particle_hyphen', input: 'Siz kelasiza va uyda kitob bor-mi?', expectError: true, expectedWord: 'kelasiza', expectedSuggestion: 'kelasiz-a' },
  { id: 345, category: 'particle_hyphen', input: 'Men-ku bu xabarni bilaman.', expectError: false },
  { id: 346, category: 'particle_hyphen', input: 'U shaharda ishlaydi.', expectError: false },
  { id: 347, category: 'particle_hyphen', input: 'Savolni men-chi beraman?', expectError: false },
  { id: 348, category: 'particle_hyphen', input: 'Bola hovlida oʻynadi.', expectError: false },
  { id: 349, category: 'particle_hyphen', input: 'Bu kichik xona.', expectError: false },
  { id: 350, category: 'particle_hyphen', input: 'U darsda javob berdi.', expectError: false },

  { id: 351, category: 'particle_joined', input: 'Uyda kitob bor-mi?', expectError: true, expectedWord: 'bor-mi', expectedSuggestion: 'bormi' },
  { id: 352, category: 'particle_joined', input: 'U bugun keladi-yov.', expectError: true, expectedWord: 'keladi-yov', expectedSuggestion: 'keladiyov' },
  { id: 353, category: 'particle_joined', input: 'Ishni tugatgan-oq joʻnadi.', expectError: true, expectedWord: 'tugatgan-oq', expectedSuggestion: 'tugatganoq' },
  { id: 354, category: 'particle_joined', input: 'Bu gapni aytgan-mi?', expectError: true, expectedWord: 'aytgan-mi', expectedSuggestion: 'aytganmi' },
  { id: 355, category: 'particle_joined', input: 'Sizda vaqt bormi?', expectError: false },
  { id: 356, category: 'particle_joined', input: 'U boʻladimi deb soʻradi.', expectError: false },
  { id: 357, category: 'particle_joined', input: 'Borgandayoq menga yozdi.', expectError: false },
  { id: 358, category: 'particle_joined', input: 'U keladi mi, bilmayman.', expectError: false },
  { id: 359, category: 'particle_joined', input: 'Bu gap ki juda muhim.', expectError: false },
  { id: 360, category: 'particle_joined', input: 'Faqat shu gina qoldi.', expectError: false },

  { id: 361, category: 'possessive_ning', input: 'Ukamni kitobi stol ustida, lekin savol bor-mi?', expectError: true, expectedWord: 'Ukamni', expectedSuggestion: 'Ukamning' },
  { id: 362, category: 'possessive_ning', input: 'Dadamni mashinasi hovlida.', expectError: true, expectedWord: 'Dadamni', expectedSuggestion: 'Dadamning' },
  { id: 363, category: 'possessive_ning', input: 'Akamni doʻsti bugun keldi.', expectError: true, expectedWord: 'Akamni', expectedSuggestion: 'Akamning' },
  { id: 364, category: 'possessive_ning', input: 'Onamni xonasi juda katta.', expectError: true, expectedWord: 'Onamni', expectedSuggestion: 'Onamning' },
  { id: 365, category: 'possessive_ning', input: 'Kartani oldi va uyga ketdi.', expectError: false },
  { id: 366, category: 'possessive_ning', input: 'Manzilni soʻradi.', expectError: false },
  { id: 367, category: 'possessive_ning', input: 'Men qarzni berdim.', expectError: false },
  { id: 368, category: 'possessive_ning', input: 'Kitobni muqovasi yirtilgan.', expectError: true, expectedWord: 'Kitobni', expectedSuggestion: 'Kitobning' },
  { id: 369, category: 'possessive_ning', input: 'Bolani koʻrgan odam keldi.', expectError: false },
  { id: 370, category: 'possessive_ning', input: 'Doʻstimni kutdim, keyin ketdim.', expectError: false },

  { id: 371, category: 'reduplicative_hyphen', input: 'Hamma narsa joy joyida.', expectError: true, expectedWord: 'joy joyida', expectedSuggestion: 'joy-joyida' },
  { id: 372, category: 'reduplicative_hyphen', input: 'Ishni bugun erta tugatamiz.', expectError: true, expectedWord: 'bugun erta', expectedSuggestion: 'bugun-erta' },
  { id: 373, category: 'reduplicative_hyphen', input: 'Ular erta kech ishlaydi.', expectError: true, expectedWord: 'erta kech', expectedSuggestion: 'erta-kech' },
  { id: 374, category: 'reduplicative_hyphen', input: 'Rasm oq qora rangda.', expectError: true, expectedWord: 'oq qora', expectedSuggestion: 'oq-qora' },
  { id: 375, category: 'reduplicative_hyphen', input: 'Buyumlar joy-joyida turibdi.', expectError: false },
  { id: 376, category: 'reduplicative_hyphen', input: 'Bu oq-qora surat.', expectError: false },
  { id: 377, category: 'reduplicative_hyphen', input: 'U erta-kech kitob oʻqiydi.', expectError: false },
  { id: 378, category: 'reduplicative_hyphen', input: 'Kun kun bilan oʻtadi.', expectError: false },
  { id: 379, category: 'reduplicative_hyphen', input: 'U sekin sekin gapirdi.', expectError: false },
  { id: 380, category: 'reduplicative_hyphen', input: 'Men kitob kitob deb takrorladim.', expectError: false },

  { id: 381, category: 'bolmasa_person', input: 'Men boʻlmasa, akam ishni tugatadi.', expectError: true, expectedWord: 'boʻlmasa', expectedSuggestion: 'boʻlmasam' },
  { id: 382, category: 'bolmasa_person', input: 'Men uyda boʻlmasa, unga qoʻngʻiroq qiling.', expectError: true, expectedWord: 'boʻlmasa', expectedSuggestion: 'boʻlmasam' },
  { id: 383, category: 'bolmasa_person', input: 'U boʻlmasam, uchrashuv boshlanmaydi.', expectError: true, expectedWord: 'boʻlmasam', expectedSuggestion: 'boʻlmasa' },
  { id: 384, category: 'bolmasa_person', input: 'ULAR BOʻLMASAM, reja oʻzgaradi.', expectError: true, expectedWord: 'BOʻLMASAM', expectedSuggestion: 'BOʻLMASA' },
  { id: 385, category: 'bolmasa_person', input: 'Men boʻlmasam, akam keladi.', expectError: false },
  { id: 386, category: 'bolmasa_person', input: 'U boʻlmasa, singlisi yordam beradi.', expectError: false },
  { id: 387, category: 'bolmasa_person', input: 'Bugun yoki boʻlmasa ertaga boramiz.', expectError: false },
  { id: 388, category: 'bolmasa_person', input: 'Men aytdim: u boʻlmasa ham boshlaymiz.', expectError: false },
  { id: 389, category: 'bolmasa_person', input: 'Yaxshi odam boʻlmasam, doʻstlarim kelarmidi?', expectError: false },
  { id: 390, category: 'bolmasa_person', input: 'Kerak boʻlmasa, qaytarib bering.', expectError: false },

  { id: 391, category: 'xalos_xolos', input: 'U nihoyat qarzdan xolos boʻldi.', expectError: true, expectedWord: 'xolos', expectedSuggestion: 'xalos' },
  { id: 392, category: 'xalos_xolos', input: 'Bola xavfdan xolos boʻldi.', expectError: true, expectedWord: 'xolos', expectedSuggestion: 'xalos' },
  { id: 393, category: 'xalos_xolos', input: 'Menda bitta xalos bor.', expectError: true, expectedWord: 'xalos', expectedSuggestion: 'xolos' },
  { id: 394, category: 'xalos_xolos', input: 'Bu shunchaki hazil xalos.', expectError: true, expectedWord: 'xalos', expectedSuggestion: 'xolos' },
  { id: 395, category: 'xalos_xolos', input: 'U tashvishdan xalos boʻldi.', expectError: false },
  { id: 396, category: 'xalos_xolos', input: 'Men buni aytdim, xolos.', expectError: false },
  { id: 397, category: 'xalos_xolos', input: 'Bu faqat taklif, xolos.', expectError: false },
  { id: 398, category: 'xalos_xolos', input: 'Gap shu xolos.', expectError: false },
  { id: 399, category: 'xalos_xolos', input: 'U balodan xalos qildi.', expectError: false },
  { id: 400, category: 'xalos_xolos', input: 'Shu bilan xolos.', expectError: false },

  { id: 401, category: 'suffix_li_lik', input: 'Bu besh oyli bola.', expectError: true, expectedWord: 'oyli', expectedSuggestion: 'oylik' },
  { id: 402, category: 'suffix_li_lik', input: 'Biz ikki kunli safarga chiqdik.', expectError: true, expectedWord: 'kunli', expectedSuggestion: 'kunlik' },
  { id: 403, category: 'suffix_li_lik', input: 'U uch yilli reja tuzdi.', expectError: true, expectedWord: 'yilli', expectedSuggestion: 'yillik' },
  { id: 404, category: 'suffix_li_lik', input: 'Bir soatli dars boshlandi.', expectError: true, expectedWord: 'soatli', expectedSuggestion: 'soatlik' },
  { id: 405, category: 'suffix_li_lik', input: 'Bu juda tuzli ovqat.', expectError: false },
  { id: 406, category: 'suffix_li_lik', input: 'Stolda suvli idish turibdi.', expectError: false },
  { id: 407, category: 'suffix_li_lik', input: 'Besh oylik bola uxlayapti.', expectError: false },
  { id: 408, category: 'suffix_li_lik', input: 'Uzoq muddatlik reja kerak.', expectError: false },
  { id: 409, category: 'suffix_li_lik', input: 'U toshkentlik oʻqituvchi.', expectError: false },
  { id: 410, category: 'suffix_li_lik', input: 'Bolalik xotiralari qadrli.', expectError: false },

  { id: 411, category: 'lar_giz', input: 'Xush keldingizlar!', expectError: true, expectedWord: 'keldingizlar', expectedSuggestion: 'keldingiz' },
  { id: 412, category: 'lar_giz', input: 'Siz vazifani yozdingizlar.', expectError: true, expectedWord: 'yozdingizlar', expectedSuggestion: 'yozdingiz' },
  { id: 413, category: 'lar_giz', input: 'Nega kech qoldingizlar?', expectError: true, expectedWord: 'qoldingizlar', expectedSuggestion: 'qoldingiz' },
  { id: 414, category: 'lar_giz', input: 'Hammangiz kitobni oʻqidingizlar.', expectError: true, expectedWord: 'oʻqidingizlar', expectedSuggestion: 'oʻqidingiz' },
  { id: 415, category: 'lar_giz', input: 'Xush keldingiz!', expectError: false },
  { id: 416, category: 'lar_giz', input: 'Siz vazifani yozdingiz.', expectError: false },
  { id: 417, category: 'lar_giz', input: 'Kech qoldilaringiz.', expectError: false },
  { id: 418, category: 'lar_giz', input: 'Bolalaringiz maktabga ketdi.', expectError: false },
  { id: 419, category: 'lar_giz', input: 'Kitoblaringiz stol ustida.', expectError: false },
  { id: 420, category: 'lar_giz', input: 'Uylaringiz juda katta.', expectError: false },
];
